

mybatis:
  type-aliases-package: com.baizhi.entity

spring:
  profiles:
    active: product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver